- source/compiler/sc3.c
Fix for #64, #114.
<del>Just removed two lines that give a crash. I've tested this very much and it pretty stable.</del>
<del>Why it stable? Because in latest Pawn these lines also does not exist: [sc3.c#L2331-L2333](https://github.com/compuphase/pawn/blob/master/compiler/sc3.c#L2331-L2333). And I think it's a good reason to remove this.</del>
> Remove Linux crash lines (#64, #114)

- source/compiler/sc1.c
- source/compiler/sc2.c
- source/compiler/sc6.c
allows negative numbers in #emit
fix for #125
> allow negative numbers in #emit & changes to public variable behaviour

- source/compiler/sc2.c
Example:
````pawn
#emit PUSH.C 1.0
#emit PUSH.C -1.0
#emit PUSH.C 8
#emit SYSREQ.C floatadd
````
> Allow float negative numbers in #emit

- source/compiler/sc1.c
- source/compiler/sc5.c
See #134
Example:
```pawn
enum static {
s_1,
s_2
};
```
or
```pawn
enum static Abc {
};
static var1[Abc];
```
or
```pawn
static enum Abc {
};
static var1[Abc];
```
> #134: Proposal: enum limited to single file scope

- source/compiler/CMakeLists.txt
Just as the title says, the bugs fixed in this PR are minor and only show up if script `compiler/CMakeLists.txt` is used from another CMake script (with `add_subdirectory`).
1. When generating a project CMake can't find file `version.h`. `CMAKE_CURRENT_BINARY_DIR` and `CMAKE_BINARY_DIR` variables are used as if they are interchangeable while they actually aren't.
`configure_file` command saves files into `CMAKE_CURRENT_BINARY_DIR` directory by default, not into `CMAKE_BINARY_DIR`.
2. For some reason when I compile the project (with `compiler/CMakeLists.txt` used from another CMake script too) with MinGW, it builds libpawnc.dll instead of pawnc.dll and pawncc.exe won't work because it needs pawnc.dll, without the "lib" prefix, so I removed it in the script.
The prefix should probably be …
> Minor fixes/adjustments for the build script

- source/compiler/sc1.c
static const Test[2][][2] = { { { 9, 8 } },  { { 6, 7 } } };
The above code causes a memory corruption as the compiler does not
correctly calculate the size of the array.
This commit adds code to fix it.
> fixes memory corruption with multi-dimensional arrays

- source/compiler/sc1.c
Solves the bug described in issue #117
new [][2][3] = { //default values };
The compiler does not create enough room for the indirection tables and
hence adjust_indirectiontables overwrites the default values leaving the
array wrongly initilized.
Adds a generic code which works for any n-dimensional arrays (n = 1,
2,3,4,5... infinity). The code fixes the issue for any dimension but the
number of dimensions is limited to 4 (sDIMEN_MAX). A review of this code
won't be required if the limit is increased in the future.
> fixes multi-dimesional array initilization bug

- readme.md
I'd like to suggest to add an `Installation on openSUSE/SLES` section to the README. One year ago, I started packaging your project for openSUSE distributions. The plan was to provide a package that everyone can install with openSUSE's package manager `zypper`. The package gets updated to the newest version when you release a new update. Users can then obtain the newest version when they update their distribution (command: `zypper up` ; would be equal to `apt-get update` on Debian/Ubuntu)
This makes it easier for users that have more than one computer/server to update to the newest version of this project.
I also planned to submit this package to the openSUSE distribution so that new released openSUSE distributions (next will be `Leap 42.3`) provide that package by default.
> Add 'Installation on openSUSE/SLES' section to README

- source/compiler/sc1.c
fix for issue #159 
When constants are passed as compiler arguments (`pawnc test.pwn myvar=10`), the compiler adds them to the symbol table using [add_constant](https://github.com/Zeex/pawn/blob/master/source/compiler/sc1.c#L1203). Before the compiler begins to parse the script, it[ removes all the symbols from the symbol table except the builtin/predefined constants](https://github.com/Zeex/pawn/blob/master/source/compiler/sc1.c#L583). While most of the symbols are added back to the symbol table as the script is parsed, the symbols passed as compiler arguments won't be added again (as the compiler options are not parsed again).
This PR changes the `add_constant` function call with `add_builtin_constant` so that the constants passed through the argument list is treated as a predefined …
> fixes deletion of constants passed a compiler args during parse

- source/compiler/sc2.c
The `#warning` and `#pragma deprecated` directives print the new line characters which are part of the user entered string. As the message formats for both these already contain a new line character at the end, the aforementioned directives printed two new lines.
This commit adds code to discard the new line characters from user string.
In case of an allocation failure, the compiler falls back to the old code.
Resolves Issue: #187
> remove extra new lines from #warning and #pragma deprecated

- source/compiler/sc3.c
- source/compiler/sc5.c
Related issues: #154 #161 #177
This PR adds code to send an error message when a user tries to return an array of unknown size in a function.
As shown in the aforementioned issues, returning arrays of unknown size can give unexpected results. This is the case as it is practically impossible to move contents of one array into another without knowing the size of the arrays. 
The compiler aborts (due to a failed assertion) when an array of unknown size is being returned (unless a release build of the compiler is being used). This PR changes it to an error message.
> trigger error if an array of unknown size is being returned

- source/compiler/libpawnc.c
- source/compiler/sc.h
- source/compiler/sc1.c
- source/compiler/sc5.c
> -E warnings as errors.

- appveyor.yml
- source/compiler/CMakeLists.txt
- source/compiler/hashmap/LICENSE
- source/compiler/hashmap/hashmap.c
- source/compiler/hashmap/hashmap.h
- source/compiler/sc.h
- source/compiler/sc1.c
- source/compiler/sc2.c
- source/compiler/sc4.c
- source/compiler/sc7.c
- source/compiler/scvars.c
This PR improves overall compile speed by a factor of ~10.
Special thanks to @Daniel-Cortez for several changes.
> Performance improvements

- source/compiler/sc1.c
```Pawn
test()
{
my_label:
// ...
if (/* ... */)
goto my_label; // the jump is made to the place of the 2'nd
// definition of 'my_label' below
// ...
my_label: // before this PR there are no errors/warnings at label redefinition
}
```
After this PR the compiler issues error 021 ('symbol already defined: "my_label"').
The same bug has been fixed in Pawn 4.0 a year ago.
> Do not allow to redefine labels

- source/compiler/sc2.c
#155
Example:
```pawn
#define foo(%1,%2) %1##%2
main() {
new barbaz;
printf("%d", foo(bar, baz));
}
```
> Tokenisation operator

- source/compiler/sc2.c
This reverts a part of https://github.com/Southclaws/pawn/commit/693591bdc3491133f2aa90498c4ad8d3aadd0eb7 which caused issues as described in #226.
https://github.com/Southclaws/pawn/commit/e7ecf386f8e82ed03a3627712d2064940c61aeb4 added code A and code B.
https://github.com/Southclaws/pawn/commit/693591bdc3491133f2aa90498c4ad8d3aadd0eb7 removed code A.
This PR removes code B; essentially reverting the fix.
Might add more commits to the PR later if not merged.
> stop removing `'\a`  (internal multi-line delimiter)

- source/compiler/sc1.c
fix for #220 
In `initarray`, `prev1` and `prev2` are dangling pointers. When assigned, they point to an address of an item in the literal queue. The compiler checks (`litadd`) the literal queue size before adding an element. If the size isn't sufficient to hold another element, it reallocates the literal queue to accommodate more items. When the reallocation happens, the previous references (`prev1` and `prev2`) to the elements of the literal queue are invalidated. De-referencing the broken pointers will cause undefined behavior.
This commit replaces the pointers with indexes. The indexes are invariant to the reallocation.
> replaces dangling pointers in initarray with indexes

- source/compiler/pawndisasm.c
Fixes #179.
Test code:
```Pawn
native random(max);
main()
{
static x;
switch (random(1))
{
case 1: x = 1;
default:x = 0;
}
#pragma unused x
}
```
`pawndisasm` output before this patch:
```
00000000  halt 00000000
00000008  proc 
0000000c  break 
00000010  break 
00000014  push.c 00000001
0000001c  push.c 00000004
00000024  sysreq.c 00000000	; random
0000002c  stack 00000008
00000034  switch 000000a0
0000003c  break 
00000040  const.pri 00000001
00000048  stor.pri 00000000
00000050  jump 00000080
00000058  break 
0000005c  zero 00000000
00000064  jump 00000080
0000006c  casetbl 00000001 00000058
00000001 0000003c
00000080  zero.pri 
00000084  retn 
```
Note the address after the `switch` instruction is incorrect, the case table (`casetbl`) is at `0000006c`, not `000000a0`.
Output after the …
> pawndisasm: Fix 'switch' argument

- source/compiler/sc7.c
In this patch I've replaced loops with `CHECK_STGPIPE`/`CHECK_STGBUFFER` checks at every iteration with a single buffer growth check and a `memcpy` call.
This doesn't do much performance-wise, but I think it's still good to have.
Also it seems that the same kind of optimisation has already been applied in `stgwrite` within the `else` branch, but for some reason not within the `if (staging)` branch.
> Optimize string copying in rebuffer() and stgwrite()

- source/compiler/sc1.c
- source/compiler/sc3.c
- source/compiler/sc5.c
Fixes #276 
```
f1(arr[]) {
new a = arr[0];
#pragma unused a
}
f2(arr[5]) {
new a = arr[0];
#pragma unused a
}
f3(const arr[]) {
new a = arr[0];
#pragma unused a
}
f4(const arr[5]) {
new a = arr[0];
#pragma unused a
}
main () {
f1("test");
f2("test");
f3("test");
f4("test");
new arr[5];
f1(arr);
f2(arr);
f3(arr);
f4(arr);
f1(arr[0]);
//f2(arr[0]); - array size must match
f3(arr[0]);
//f4(arr[0]); - array size must match
}
```
```
test.pwn(1) : warning 214: possibly a "const" array argument was intended: "arr"
test.pwn(6) : warning 214: possibly a "const" array argument was intended: "arr"
test.pwn(20) : warning 239: literal array/string passed to a non-const parameter
test.pwn(21) : warning 239: …
```
> suggest `const` qualifier for arguments and inform user when an array/string literal is passed as a non-const argument

- source/compiler/sc.h
- source/compiler/sc1.c
- source/compiler/sc4.c
- Skips function preamble (`PROC` instruction) on naked functions
Fixes #324 
Assembly output demonstrating the new feature:
test1.pwn:
```pawn
#pragma naked
f(a)
{
#emit LOAD.S.pri a
#emit RETN
}
main()
{
f(5);
}
```
test1.asm:
```asm
CODE 0	; 0
;program exit point
halt 0
; f
; line 3
;$lcl a c
load.s.pri c
retn 
proc	; main
; line 9
; line a
break	; 18
push.c 5
;$par
push.c 4
call .f
;$exp
zero.pri
retn
STKSIZE 1000
```
test2.pwn:
```pawn
f(a)
{
#emit LOAD.S.pri a
#emit RETN
}
main()
{
f(5);
}
```
test2.asm:
```asm
CODE 0	; 0
;program exit point
halt 0
proc	; f
; line 2
;$lcl a c
load.s.pri c
retn 
zero.pri
retn
proc	; main
; line 8
; line 9
break	; 24 …
```
> Don't generate function preamble on naked functions

- source/amx/amxaux.c
Fixes bugs introduced in 44312b96532cc1056a9f6e46bec82525d5a53229 (the interpreter won't close the AMX file if `aux_ProgramSize()` or `aux_LoadProgram()` couldn't read the data from it). Not that these bugs matter much (the file is closed automatically by the OS when the interpreter process is terminated anyway), but I believe it still would be right to fix them.
-
> amxaux.c: Don't forget to close the program file before returning

- source/compiler/sc2.c
- source/compiler/tests/empty_warning_crash_gh_339.meta
- source/compiler/tests/empty_warning_crash_gh_339.pwn
- Because I want a free T shirt. Also non crashing compilers are cool.
Fixes #339 
> Fix empty warnings causing crashes

- source/compiler/sc3.c
- source/compiler/tests/empty_symbol_name_indeterminate_array_size_gh_338.meta
- source/compiler/tests/empty_symbol_name_indeterminate_array_size_gh_338.pwn
- source/compiler/tests/md_array_size_chk_gh_314.meta
- Fixes the below issue
Fixes #338 
> Show symbol name with indeterminate array size warning

- source/compiler/sc.h
- source/compiler/sc1.c
- source/compiler/sc2.c
- source/compiler/sc4.c
This moves the `-l` code output to after the second pass, so that the generated code is the most accurate it can be.
-
Fixes #116
> Write `.lst` after the second pass.

- source/amx/amx.h
- source/amx/amxFile.rc
- source/amx/amxFloat.rc
- source/amx/amxargs.c
- source/amx/amxargs.def
- source/amx/amxargs.rc
- source/amx/amxcons.c
- source/amx/amxcore.c
- source/amx/amxfile.c
- source/amx/amxfloat.c
- source/amx/amxstring.c
- source/amx/amxstring.rc
- source/amx/amxtime.c
- source/amx/amxtime.rc
- source/amx/minGlue.h
- source/amx/minIni.c
- source/amx/minIni.h
Backport natives and features from PAWN 4.
Fixes #
This takes the default natives from PAWN 4 and puts them in PAWN 3.
> Back-ported some PAWN 4 natives and features.

- source/compiler/sc5.c
- source/compiler/tests/gh_353_symbol_suggestions.meta
- source/compiler/tests/gh_353_symbol_suggestions.pwn
This PR fixes the problem where after the 1'st pass the compiler suggests global variables before the point of their definition:
```Pawn
GetValue()
{
return value; // error 017: undefined symbol "value"; did you mean "value"?
}
new value = 0;
main()
{
GetValue();
}
```
-
-
> Fix the compiler suggesting unimplemented variables

- readme.md
I decided to create a separate project on [OBS](https://build.opensuse.org/project/show/home:mschnitzer:pawncc) to split the pawncc compiler versions from other packages for openSUSE.
Changes:
* The pawncc packages for openSUSE were moved to a separate project on the Open Build Service. The link points now to the correct location.
* Added an instruction for installing multiple pawncc compiler versions on openSUSE
**Additional Documentation/Information**:
I will drop the packages from the old project on OBS (https://build.opensuse.org/package/show/home:mschnitzer/pawncc) when this PR gets into master. As long as it will be just in dev, the old links will still work.
> Adjust openSUSE installation guide

- source/compiler/pawndisasm.c
* Fixed input and output files not being properly closed and `code` being leaked on early returns.
* Implemented proper handling for invalid instructions.
Now instead of crashing on invalid instructions (due to OOB access to the opcode table) `pawndisasm` prints a proper error message with the code of invalid instruction and the address it was detected at.
* Removed extra space after AMX flags.
* Code cleanup.
* Removed unused data from the opcode table.
It seems that the opcode table was copied from `sc6.c` and sorted by opcode IDs instead of alphabetical order, but field `OPCODE::opcode` was left unused.
* Removed opcode handler `do_switch()` (it was a duplicate of `do_jump()`).
* Function `casetbl()` has been renamed into `do_casetbl()` to be …
> pawndisasm: Minor fixes, code cleanup

- source/compiler/sc.h
- source/compiler/sc1.c
- source/compiler/sc3.c
- source/compiler/sc5.c
- source/compiler/tests/gh_353_symbol_suggestions.meta
- source/compiler/tests/gh_353_symbol_suggestions.pwn
This PR fixes the following bugs related to error suggestions:
* Functions aren't suggested before the point of their definition/implementation:
```Pawn
main()
{
// The compiler is supposed to suggest "DoNothing" here, but it doesn't,
// even though Pawn functions can be called before being declared/implemented.
DoNothin(); // error 017: undefined symbol "DoNothin"
}
DoNothing(){}
```
* Failed assertion when `tagof` is used on a string or numeric literal:
```Pawn
main()
{
// This gives an "assertion failed" message if the compiler is built
// with assertions enabled
return tagof(0);
}
```
> More fixes related to suggestions

- source/compiler/memfile.c
- source/compiler/sc.h
- source/compiler/sc1.c
- source/compiler/sc2.c
- source/compiler/sc3.c
- source/compiler/sc4.c
- source/compiler/sc6.c
- source/compiler/sc7.c
- source/compiler/sci18n.c
- source/compiler/sclist.c
- source/compiler/scstate.c
Fixes for various minor bugs that weren't worth making a separate PR for each of them:
* Fixed invalid formula for calculating array size (in characters) in function `hier1()`.
The cell size in bits was hardcoded as `32` (should be `sizeof(cell)*8`), which could lead to generation of invalid code for array boundary checks if the Pawn toolkit was configured with 16- or 64-bit cell size.
Of course, this bug doesn't affect SA-MP (which is 32-bit), but I think it's still good to have this fix here.
* Fixed invalid type cast in `funcstub()`.
See https://github.com/pawn-lang/compiler/issues/296#issuecomment-450643026.
* Fixed OOB array access in `encode_cell()`.
This one seems to originate from a commit that I made a year and a half ago (sorry!)
* Fixed …
> Misc. minor fixes

- source/compiler/sc2.c
- source/compiler/tests/gh_373.meta
- source/compiler/tests/gh_373.pwn
Adds `#pragma unwritten list, of, variables` and `#pragma unread more, variables`.  They are basically identical to `#pragma unused`, but only set either `uREAD` or `uWRITTEN` instead of both.  This makes intent clearer, especially when you don't write to a non-const array parameter.  This will suppress the `possibly-const` warning without the slightly odd-looking code of marking a clearly used variable as `unused`.  Basically, this just more clearly expresses intent.
Fixes #373 
Possible solution to #371 and previous discussions (no issue number) about what to do about arrays passed to public callbacks.  Currently they are ignored.
> Branch pragma unwritten

- source/compiler/sc.h
- source/compiler/sc1.c
- source/compiler/sc2.c
- source/compiler/tests/gh_258.meta
- source/compiler/tests/gh_258.pwn
Addes `#pragma nodestruct list, of, vars` to suppress generation of destructor code on their scope exit.
Fixes #258 
> Branch pragma nodestruct

- source/compiler/sc1.c
- source/compiler/sc3.c
- source/compiler/tests/gh_436_local_var_self_init.meta
- source/compiler/tests/gh_436_local_var_self_init.pwn
Fixes variables being able to be self-assigned through initialization expressions (#420).
Example:
```Pawn
main()
{
// Before the fix: no error
// After: error 017: undefined symbol "test"
new test = test;
}
```
The problem is that the compiler creates symbol `test` before generating the code for its initialization expression, so `test` can be used in that expression.
This PR simply makes the compiler temporarily mark the newly created symbol as undefined (until the code for the initialization expression is emitted) and issue an error if the symbol for a local variable is undefined.
Fixes #420
> Do not allow variables to be self-assigned through initialization

- source/compiler/sc2.c
Fixes #426 
Makes the compiler slightly more future-proof by allowing us to do something like:
```pawn
#if __Pawn >= 0x03AB
#message You're on a nice new compiler.
#endif
```
Currently to do that you need to do:
```pawnc
#message You're on a nice new compiler.
```
```pawn
#if __Pawn >= 0x03AB
#include "message.inc"
#endif
```
Or you get an error that `#message` (or anything else) is an unknown directive if the compiler doesn't recognise it, even if it is disabled.
The only downside to this is that it makes it slightly harder to add new `#if`-like directives:
```pawn
#if __Pawn >= 0x03AB
#message You're on a nice new compiler.
#elif SHOW_ERROR
#error You've got an error.
#endif
```
A compiler that fails the first check AND doesn't recognise `#elif` will simply skip it and go all the way to …
> Ignore `#if`d out unknown directives.

- source/compiler/sc1.c
Fixes data for predefined arrays being put into the assembler file before everything else, which causes an assertion failure (#156).
Usually the compiler puts code/data into the assembler file in the following order:
1. The program exit point (`halt 0`).
2. (optional) The exit point for functions called from the wrong state (`halt d`).
3. (optional) Data for automatons.
4. (optional) Code for stubs and jump tables for state functions.
But if at least one of predefined string constants (`__file`, `__date`, `__time`) is used, the compiler puts their data into the assembler file before everything else, thus breaking that order.
And if there's at least one state function in the script, then assertion `glb_declared==0` in function `writeleader()` (file …
> Fix assertion failure `glb_declared==0`

- source/compiler/sc5.c
- source/compiler/tests/gh_353_symbol_suggestions.meta
- source/compiler/tests/gh_353_symbol_suggestions.pwn
Fixes incorrect suggestions for state variables used out of state scope.
Example (from #405):
```Pawn
new var <state_a>;
main()
{
var = 5;
}
```
Error message before the fix:
```
test.pwn(5) : error 017: undefined symbol "var"; did you mean "var"?
```
After:
```
test.pwn(5) : error 017: undefined symbol "var"; state variable out of scope
```
Fixes #405
> Fix incorrect suggestions for state variables

- source/compiler/sc2.c
- Title says it all!
Fixes #359
For some reason `i` will be `32` after our for loop so an OOB happens when code tries to assign `'\0'` to `name[32]` since `name` size is 32.
Doing a `-1` to `i` fixed this issue and now throws 
```
error 038: extra characters on line
```
when character count is over 31.
Also I'm not sure if I should change `name` size and make it able to accept more than 31 characters, since file paths can be more than 31 characters of course
> fix "#pragma option" crash when character count is over 31

- source/compiler/sc1.c
- source/compiler/tests/anonymous_enum_tags.meta
- source/compiler/tests/anonymous_enum_tags.pwn
This PR fixes a problem with the compiler silently ignoring tags inside the braces of unnamed enums.
Before:
```Pawn
enum
{
Float:DRAW_DISTANCE = 100.0 // This code compiles, but the 'Float' tag
// is silently ignored and the constant is defined
// as "DRAW_DISTANCE = _:100.0", so if someone uses it,
// then instead of "100.0" they'll get "float(_:100.0)"
};
```
After:
```Pawn
enum
{
Float:DRAW_DISTANCE = 100.0 // error 001: expected token: "-identifier-", but found "-label-"
};
```
Fixes #444
> Do not allow tags inside the braces of unnamed enums

- source/compiler/sc1.c
See #429 for the explanation on how to reproduce the bug.
https://github.com/pawn-lang/compiler/blob/2f642899f1eb283ea5c40143b98112eb9fc19568/source/compiler/sc1.c#L2079-L2081
It seems that the original author of this code meant to write `sym->states->next!=NULL` instead of `sym->next!=NULL` (note that in this fork the same should be written as `sym->states->first!=NULL` because we have `constvalue_root`). This is confirmed by the fact that `sym->states->first` (or `sym->states->next` in the original code) gets dereferenced right after that subexpression (`sym->states->first->index==sc_curstates`).
Fixes #429
> Fix assertion failure whence the script contains a single state variable

- source/compiler/sc2.c
```pawn
#define MAX_PLAYERS (500)
new str[] = #MAX_PLAYERS;
```
That will currently fail, because the `)` will end the string too early.  This, very simply, just allows this to be stringised by counting the number of `(`s and `)`s.  It doesn't end the string until the are matched.
Fixes #
> Track the depth of `()`s in `#` strings.

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- readme.md
This change just improves the wording around contribution in the readme, contributing and PR template to ensure contributors discuss proposed changes before actually writing any code to save time during code review.
> elaborated on contribution guidelines

- source/compiler/sc1.c
- source/compiler/tests/switch-case-tag-control.meta
- source/compiler/tests/switch-case-tag-control.pwn
Fixes an oversight with the compiler not checking the `switch`/`case` values for tag mismatch, as described in #468.
Fixes #468 
> Check switch/case values for tag mismatch

- source/compiler/sc1.c
- source/compiler/tests/gh_217.meta
- source/compiler/tests/gh_217.pwn
Removes the deprecation warning on function declarations, only keeps them on uses.
Fixes #242
The previous attempt didn't take in to account declaring `public` functions whose `forward` marked them as deprecated.  This does (and is actually way simpler).
> Reimplement #242, taking public functions in to account.

- source/compiler/sc.h
- source/compiler/sc1.c
- source/compiler/tests/tagof_tag_argdefault.meta
- source/compiler/tests/tagof_tag_argdefault.pwn
Allows to use `tagof(Tag:)` as a default value for function arguments (see #485).
Fixes #485
> Allow to use `tagof(Tag:)` as a default argument value

- source/compiler/sc3.c
- source/compiler/tests/warning_047.meta
- source/compiler/tests/warning_047.pwn
Fixes an incorrect error message that originates from a typo in the error code (`error(7)` instead of `error(47)`) made by the original Pawn author.
The bug can be reproduced by passing a cell from a passed-by-reference array to a function that is supposed to take a fixed-length array instead:
```Pawn
Func2(const arr[3])
{
return arr[0];
}
Func1(const arr[])
{
Func2(arr[0]); // error 007: operator cannot be redefined
}
main()
{
static const arr[1];
Func1(arr);
}
```
In this example the correct error message should be `error 047: array sizes do not match, or destination array is too small`, not `error 007: operator cannot be redefined`.
Fixes #
> Fix incorrect error message (007 => 047)

- source/compiler/sc3.c
- source/compiler/tests/gh_517.meta
- source/compiler/tests/gh_517.pwn
- source/compiler/tests/gh_517_pcode.meta
- source/compiler/tests/gh_517_pcode.pwn
Fixes the compiler not calling user-defined assignment operator for compound assignments, as described in #517.
Fixes #517 
> Fix user-defined assignment operators not being called for compound assignments

- source/compiler/sc1.c
- source/compiler/sc5.c
- source/compiler/tests/gh_522.meta
- source/compiler/tests/gh_522.pwn
Fixes an oversight with the compiler not checking if the operator has been declared/defined with the `public` specifier, as described in #522.
Example of how it's handled in this PR:
```Pawn
forward public operator=(Tag:a);
public operator=(Tag:a) return _:a;
```
```
test.pwn(1) : error 056: arrays, local variables, function arguments and user-defined operators cannot be public (symbol "_:operator=(Tag:)")
test.pwn(2) : error 056: arrays, local variables, function arguments and user-defined operators cannot be public (symbol "_:operator=(Tag:)")
```
At first I couldn't find any fitting message for this kind of error, so I had a choice: either add a new error message (something like `"user-defined operators cannot be public (symbol \"%s\")"`) or …
> Print an error if an operator is declared/defined as 'public'

- source/compiler/sc1.c
- source/compiler/tests/gh_525.meta
- source/compiler/tests/gh_525.pwn
Fixes assertion failure when the user forgets to specify a function the native operator is based on, as described in #524.
Fixes #524 
> Fix assertion failure when a native operator is declared without a base function
